# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleExtreme <- function(mu, sd, lower, upper) {
    .Call('selectivefmri_sampleExtreme', PACKAGE = 'selectivefmri', mu, sd, lower, upper)
}

sampleUnivTruncNorm <- function(mu, sd, lower, upper) {
    .Call('selectivefmri_sampleUnivTruncNorm', PACKAGE = 'selectivefmri', mu, sd, lower, upper)
}

sampleTruncNorm <- function(sample, lower, upper, mean, precision, cycles) {
    .Call('selectivefmri_sampleTruncNorm', PACKAGE = 'selectivefmri', sample, lower, upper, mean, precision, cycles)
}

