# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleTruncNorm <- function(sample, lower, upper, mean, sigma, condSigma, cycles) {
    .Call('selectivefmri_sampleTruncNorm', PACKAGE = 'selectivefmri', sample, lower, upper, mean, sigma, condSigma, cycles)
}

